Spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: coupon_route
          uri: lb://qxmall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: product_route
          uri: lb://qxmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://qxmall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://qxmall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://qxmall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: qxmall_host_route
          uri: lb://qxmall-product
          predicates:
            - Host=qxmall.com,item.qxmall.com

        - id: qxmall_search_route
          uri: lb://qxmall-search
          predicates:
            - Host=search.qxmall.com

        - id: qxmall_auth_route
          uri: lb://qxmall-auth-server
          predicates:
            - Host=auth.qxmall.com

        - id: qxmall_cart_route
          uri: lb://qxmall-cart
          predicates:
            - Host=cart.qxmall.com

        - id: qxmall_order_route
          uri: lb://qxmall-order
          predicates:
            - Host=order.qxmall.com

        - id: qxmall_member_route
          uri: lb://qxmall-member
          predicates:
            - Host=member.qxmall.com





