spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tFYu3nrC8ascWh9iJ8t
      secret-key: bUIQv8F1ZufuXBlVQvVIam3CloFZH9
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com

  application:
    name: qxmall-third-party

server:
  port: 30000
