spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tFYu3nrC8ascWh9iJ8t
      secret-key: bUIQv8F1ZufuXBlVQvVIam3CloFZH9
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        appCode: efb750d0ea8344ef89db36bbb5a27a65
        effectiveTime: 10
        smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
        templateId: 908e94ccf08b4476ba6c876d13f084ad

  application:
    name: qxmall-third-party

server:
  port: 30000
